version: '3'
services:
  mall4j-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: mall4j-mysql
    ports:
      - 3317:3306
    volumes:
      - ./mall4j-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  mall4j-redis:
    #定义主机名
    container_name: mall4j-redis
    #使用的镜像；注意这里的版本要与第2步redis版本一致
    image: redis:6.0.6
    #容器的映射端口
    ports:
      - 6379:6379 #注意第二个端口必须是redis.conf中的端口号
    command: redis-server /etc/redis.conf
    #定义挂载点
    volumes:
      - ./data:/data #挂载/docker-compose/redis/data至容器
      - ./conf/redis.conf:/etc/redis.conf #挂载conf至容器
    privileged: true   #环境变量
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    #docker 重启后，容器自启动
    restart: always

  mall4j-admin:
    build:
      context: ../
      dockerfile: ./yami-shop-admin/Dockerfile
    restart: always
    container_name: mall4j-admin
    environment:
      REDIS_HOST: mall4j-redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: test
      MYSQL_HOST: mall4j-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: yami_shops
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8085:8085
    depends_on:
      - mall4j-redis
      - mall4j-mysql
    links:
      - "mall4j-redis"
      - "mall4j-mysql"

  mall4j-api:
    build:
      context: ../
      dockerfile: ./yami-shop-api/Dockerfile
    restart: always
    container_name: mall4j-api
    environment:
      REDIS_HOST: mall4j-redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: test
      MYSQL_HOST: mall4j-mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: yami_shops
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8086:8086
    depends_on:
      - mall4j-redis
      - mall4j-mysql
    links:
      - "mall4j-redis"
      - "mall4j-mysql"